### ISSUE TITLE
now-micro doesn't recognize function

### ISSUE THREAD

**Issue by NathanielHill** [lucasconstantino/now-micro#1]
I'm getting the following error:

`now-micro builder expects main export to be a function (object found)`

even with this simple case:
```
module.exports = (req, res) => {
res.end('Hello world')
}
```

**Comment by lucasconstantino** [comment]
@NathanielHill this is odd. I suggest you have a look at the [sample-project](https://github.com/lucasconstantino/now-micro/tree/master/test/fixtures/sample-project) inside the tests directory. In fact, it is currently deployed and working at https://sample-project-n599jvpru.now.sh! [Check it out](https://sample-project-n599jvpru.now.sh).

**Comment by NathanielHill** [comment]
Yeah, I couldn't understand it either. I read through the source, and ended up simply using the following setup with `@now/node`:

```
module.exports = (req, res) => require('micro').run(req, res, (req, res) => {
   ...
}
```

**Comment by lucasconstantino** [comment]
Probably there are some differing versions somewhere... anyway, you got it right, that's all there is to do to make your lambda more Micro friendly :O
