### ISSUE TITLE
Not compatible with `now dev`

### ISSUE THREAD

**Issue by leo** [lucasconstantino/now-micro#4]
Unfortunately, using this package with `now dev` will cause the following error:

```
Error: listen EADDRINUSE :::3000
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1367:14)
    at listenInCluster (net.js:1408:12)
    at Server.listen (net.js:1492:7)
    at Object.<anonymous> 
```

This is because the package seems to be using a harcoded port instead of one that is ephemeral. Please instead use a ephemeral one.

Even better would be if there was no server being opened. Instead, the Builder should expose a request handler `(req, res)` for maximum performance.

**Comment by TooTallNate** [comment]
Seems like the `@now/node` dependency just needs to be updated.

**Comment by jrschumacher** [comment]
@TooTallNate did you test it? I updated locally yet still having issues.

**Comment by jrschumacher** [comment]
I was able to resolve the issue. It seems that the original version was storing the change in memory, but [@now/node](https://github.com/zeit/now-builders/tree/master/packages/now-node) expects the file to be written

**Comment by jrschumacher** [comment]
@leo if you want to try this out change your builds to use my branch

```
...
"builds": [
    {
      "src": "api/**/*.js",
      "use": "jrschumacher/now-micro#update-now-dependencies"
    }
  ],
...
```
